// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'app/core/helpers/environments.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Environments.param('FIREBASE_ANDROID_API_KEY') ?? '',
    appId: Environments.param('FIREBASE_ANDROID_APP_ID') ?? '',
    messagingSenderId: Environments.param('FIREBASE_MESSAGING_SENDER_ID') ?? '',
    projectId: Environments.param('FIREBASE_PROJECT_ID') ?? '',
    storageBucket: Environments.param('FIREBASE_STORAGE_BUCKET') ?? '',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Environments.param('FIREBASE_IOS_API_KEY') ?? '',
    appId: Environments.param('FIREBASE_IOS_APP_ID') ?? '',
    messagingSenderId: Environments.param('FIREBASE_MESSAGING_SENDER_ID') ?? '',
    projectId: Environments.param('FIREBASE_PROJECT_ID') ?? '',
    storageBucket: Environments.param('FIREBASE_STORAGE_BUCKET') ?? '',
    androidClientId: Environments.param('FIREBASE_ANDROID_CLIENT_ID') ?? '',
    iosClientId: Environments.param('FIREBASE_IOS_CLIENT_ID') ?? '',
    iosBundleId: Environments.param('FIREBASE_IOS_BUNDLE_ID') ?? '',
  );
}
