class Constants {
  Constants._();

  static const BASE_URL_KEY = 'BASE_URL';
  static const REST_CLIENT_CONNECT_TIMEOUT_KEY = 'REST_CLIENT_CONNECT_TIMEOUT';
  static const REST_CLIENT_RECEIVE_TIMEOUT_KEY = 'REST_CLIENT_RECEIVE_TIMEOUT';
}
